name: cinema_reservation_client
description: Client Dart/Flutter pour l'API Reservation Billet Cinema.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.3.1
  serverpod_client: 3.3.1
